### ISSUE TITLE
Only build docs.rs for Android?

### ISSUE THREAD

**Issue by MarijnS95** [rust-mobile/android_logger-rs#76]
Using https://docs.rs/about/metadata, we should probably configure this to only generate docs for the Android platforms? Though this crate seems to compile just fine on non-Android platforms thanks to a lot of `cfg`s, is that intended?

**Comment by Dushistov** [comment]
If you want to create PR, you are welcomed. But, I can not see any `pub` item that has documentation comment, but hidden, because of `cfg`.

So resulted documentation almost not changed on docs.rs, except `PlatformLogWriter` methods, but they are not documented yet.

**Comment by Nercury** [comment]
> Though this crate seems to compile just fine on non-Android platforms thanks to a lot of `cfg`s, is that intended?

Yes, originally this helped me run tests

**Comment by MarijnS95** [comment]
@Dushistov this is what I started doing, but realized exactly that there is a lot of extra `cfg` to make it compile on non-Android. Hence there's not a lot gained by only compiling for the desired target platform, except possible links to variable types such as `c_char` which are different on Android.

@Nercury if that's no longer relevant, perhaps it is worth simplifying and removing some of that?
